version: '3'
services:

  api_db:
    image: mysql:8
    command:
      - --default-authentication-plugin=mysql_native_password
    volumes:
      - ./db-volume:/var/lib/mysql
      - ./schema:/docker-entrypoint-initdb.d
      # - db-data:/var/lib/mysql
    environment:
      - TZ=America/Sao_Paulo
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=poll_challenge
    networks:
      - api_network
    restart: always

  app:
    build: .
    environment:
      - DB_HOST=api_db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=secret
    ports:
      - "5000:80"
    depends_on:
      - api_db
    networks:
      - api_network
    restart: always

  api_phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.8
    ports:
      - "3010:80"
    environment:
      - PMA_HOST=api_db
    depends_on:
      - api_db
    networks:
      - api_network
    restart: always

# volumes:
#   db-data:

networks:
  api_network:
    driver: bridge